In [2]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('reports_v5.db')

# Read SQL query into a DataFrame
query = "SELECT * FROM reports"
df = pd.read_sql(query, conn, index_col='report_id')

# Define a function to calculate total debt
def calculate_total_debt(row):
    if row['DebtNoncurrent'] != 0:
        return row['DebtNoncurrent'] + row['DebtCurrent']
    elif row['LongTermDebtNoncurrent'] != 0:
        return row['LongTermDebtNoncurrent'] + row['DebtCurrent']
    else:
        return row['CapitalLeaseObligationsNoncurrent'] + row['FinanceLeaseLiabilityNoncurrent'] + \
               row['CapitalLeaseObligationsCurrent'] + row['LinesOfCreditCurrent'] + row['FinanceLeaseLiabilityCurrent']

# Apply the function to create a new column 'total_debt'
df['total_debt'] = df.apply(calculate_total_debt, axis=1)

# Print the DataFrame with the new column
print(df['total_debt'])

report_id
52        2.872000e+06
93        0.000000e+00
98        0.000000e+00
155       0.000000e+00
157       1.375088e+09
              ...
620429    0.000000e+00
630393    0.000000e+00
656021    4.400000e+06
657474    0.000000e+00
663874    0.000000e+00
Name: total_debt, Length: 29372, dtype: float64

In [3]:
# Calculate the total number of entries
total_entries = len(df)

# Calculate the number of entries where total_debt is equal to 0
num_zero_debt_entries = (df['total_debt'] == 0).sum()

# Calculate the percentage
percent_zero_debt_entries = (num_zero_debt_entries / total_entries) * 100

# Print the percentage
print("Percentage of entries with total_debt equal to 0:", percent_zero_debt_entries, "%")

Percentage of entries with total_debt equal to 0: 70.19950973716465 %

In [4]:
df

,sec_url,Assets,AssetsCurrent,LongTermDebtCurrent,LongTermDebtNoncurrent,ShortTermBorrowings,OtherShortTermBorrowings,ConstructionLoan,BridgeLoan,ShortTermBankLoansAndNotesPayable,...,PensionAndOtherPostretirementDefinedBenefitPlansLiabilitiesNoncurrent,StockholdersEquity,LiabilitiesAndStockholdersEquity,MinorityInterest,StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest,Revenue,Revenues,NetIncomeLoss,ProfitLoss,total_debt
report_id,,,,,,,,,,,,,,,,,,,,,
52,http://www.sec.gov/Archives/edgar/data/1000683...,2.587100e+07,1.368500e+07,235000.0,2.872000e+06,0.0,0.0,0.0,0.0,0.0,...,0.0,8.000000e+03,2.661200e+07,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.872000e+06
93,http://www.sec.gov/Archives/edgar/data/1001082...,8.688986e+09,3.774997e+09,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,-1.850705e+09,8.688986e+09,451000.0,-1.850254e+09,0.0,0.0,0.0,230915000.0,0.000000e+00
98,http://www.sec.gov/Archives/edgar/data/1001082...,1.303549e+10,5.423292e+09,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,1.017510e+08,1.303549e+10,1584000.0,1.033350e+08,0.0,0.0,0.0,318978000.0,0.000000e+00
155,http://www.sec.gov/Archives/edgar/data/1001601...,1.147600e+07,4.204000e+06,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,-1.646000e+06,4.433000e+06,7961000.0,-2.800270e+08,0.0,0.0,0.0,-4549000.0,0.000000e+00
157,http://www.sec.gov/Archives/edgar/data/1001604...,2.089940e+09,1.391420e+08,21324000.0,1.375088e+09,0.0,0.0,0.0,0.0,0.0,...,0.0,3.120820e+08,2.089940e+09,6816000.0,4.000000e+03,0.0,898732000.0,0.0,0.0,1.375088e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620429,https://www.sec.gov/Archives/edgar/data/108193...,1.143300e+05,2.953800e+04,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,6.833625e+07,1.143300e+05,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
630393,https://www.sec.gov/Archives/edgar/data/50292/...,3.048153e+07,2.358870e+07,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,2.791572e+07,3.048153e+07,0.0,0.000000e+00,0.0,13843521.0,0.0,0.0,0.000000e+00
656021,https://www.sec.gov/Archives/edgar/data/183960...,2.054190e+08,7.451100e+07,1200000.0,4.400000e+06,0.0,0.0,0.0,0.0,0.0,...,0.0,-8.284000e+06,2.269350e+08,0.0,6.950000e+07,0.0,63067000.0,0.0,0.0,4.400000e+06
657474,https://www.sec.gov/Archives/edgar/data/146897...,7.075920e+05,7.041440e+05,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,6.098117e+06,7.075920e+05,0.0,0.000000e+00,0.0,1390258.0,0.0,-470583.0,0.000000e+00
663874,https://www.sec.gov/Archives/edgar/data/146897...,2.119290e+05,2.097270e+05,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.0,-2.887608e+06,2.119290e+05,0.0,0.000000e+00,0.0,0.0,0.0,182631.0,0.000000e+00

In [5]:
import pandas as pd
import json

# Load the DataFrame
# Assuming 'df' is already defined

# Load the JSON file
with open('report_data_v2.json', 'r') as f:
    report_data = json.load(f)

# Create a dictionary to map report IDs to keys
report_id_to_key = {}
for key, reports in report_data.items():
    for report in reports:
        report_id_to_key[report['report_id']] = key

# Create a new column in the DataFrame using the mapping
df['key'] = df.index.map(report_id_to_key)

# Display the DataFrame with the new column
df

,sec_url,Assets,AssetsCurrent,LongTermDebtCurrent,LongTermDebtNoncurrent,ShortTermBorrowings,OtherShortTermBorrowings,ConstructionLoan,BridgeLoan,ShortTermBankLoansAndNotesPayable,...,StockholdersEquity,LiabilitiesAndStockholdersEquity,MinorityInterest,StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest,Revenue,Revenues,NetIncomeLoss,ProfitLoss,total_debt,key
report_id,,,,,,,,,,,,,,,,,,,,,
52,http://www.sec.gov/Archives/edgar/data/1000683...,2.587100e+07,1.368500e+07,235000.0,2.872000e+06,0.0,0.0,0.0,0.0,0.0,...,8.000000e+03,2.661200e+07,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.872000e+06,366_4Q2011
93,http://www.sec.gov/Archives/edgar/data/1001082...,8.688986e+09,3.774997e+09,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,-1.850705e+09,8.688986e+09,451000.0,-1.850254e+09,0.0,0.0,0.0,230915000.0,0.000000e+00,484_1Q2010
98,http://www.sec.gov/Archives/edgar/data/1001082...,1.303549e+10,5.423292e+09,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,1.017510e+08,1.303549e+10,1584000.0,1.033350e+08,0.0,0.0,0.0,318978000.0,0.000000e+00,484_3Q2011
155,http://www.sec.gov/Archives/edgar/data/1001601...,1.147600e+07,4.204000e+06,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,-1.646000e+06,4.433000e+06,7961000.0,-2.800270e+08,0.0,0.0,0.0,-4549000.0,0.000000e+00,737_4Q2011
157,http://www.sec.gov/Archives/edgar/data/1001604...,2.089940e+09,1.391420e+08,21324000.0,1.375088e+09,0.0,0.0,0.0,0.0,0.0,...,3.120820e+08,2.089940e+09,6816000.0,4.000000e+03,0.0,898732000.0,0.0,0.0,1.375088e+09,805_4Q2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620429,https://www.sec.gov/Archives/edgar/data/108193...,1.143300e+05,2.953800e+04,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,6.833625e+07,1.143300e+05,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,283_4Q2022
630393,https://www.sec.gov/Archives/edgar/data/50292/...,3.048153e+07,2.358870e+07,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,2.791572e+07,3.048153e+07,0.0,0.000000e+00,0.0,13843521.0,0.0,0.0,0.000000e+00,367_4Q2022
656021,https://www.sec.gov/Archives/edgar/data/183960...,2.054190e+08,7.451100e+07,1200000.0,4.400000e+06,0.0,0.0,0.0,0.0,0.0,...,-8.284000e+06,2.269350e+08,0.0,6.950000e+07,0.0,63067000.0,0.0,0.0,4.400000e+06,751_4Q2022
657474,https://www.sec.gov/Archives/edgar/data/146897...,7.075920e+05,7.041440e+05,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,6.098117e+06,7.075920e+05,0.0,0.000000e+00,0.0,1390258.0,0.0,-470583.0,0.000000e+00,737_4Q2015
663874,https://www.sec.gov/Archives/edgar/data/146897...,2.119290e+05,2.097270e+05,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,-2.887608e+06,2.119290e+05,0.0,0.000000e+00,0.0,0.0,0.0,182631.0,0.000000e+00,737_2Q2016

In [11]:
import pandas as pd

# Assuming 'df' is your DataFrame loaded with necessary data

# Filter out rows where Assets or Stockholders' Equity are zero (common filter for both scenarios)
df_filtered_common = df[(df['Assets'] != 0) & (df['StockholdersEquity'] != 0)]

# Scenario 1: Calculations including all entries
df_all = df_filtered_common.copy()
df_all['debt_to_assets_all'] = df_all.apply(lambda x: x['total_debt'] / x['Assets'] if x['total_debt'] != 0 else 0, axis=1)
df_all['debt_to_equity_all'] = df_all.apply(lambda x: x['total_debt'] / x['StockholdersEquity'] if x['total_debt'] != 0 else 0, axis=1)

# Scenario 2: Calculations excluding entries with total_debt = 0
df_exclude_zero_debt = df_filtered_common[df_filtered_common['total_debt'] != 0].copy()
df_exclude_zero_debt['debt_to_assets_exclude'] = df_exclude_zero_debt['total_debt'] / df_exclude_zero_debt['Assets']
df_exclude_zero_debt['debt_to_equity_exclude'] = df_exclude_zero_debt['total_debt'] / df_exclude_zero_debt['StockholdersEquity']

# Group by 'key' and calculate median leverage ratios and counts for both scenarios
grouped_all = df_all.groupby('key').agg(
    debt_to_assets_median_all=('debt_to_assets_all', 'median'),
    debt_to_equity_median_all=('debt_to_equity_all', 'median'),
    count_all=('debt_to_assets_all', 'size')
)
grouped_exclude_zero_debt = df_exclude_zero_debt.groupby('key').agg(
    debt_to_assets_median_exclude=('debt_to_assets_exclude', 'median'),
    debt_to_equity_median_exclude=('debt_to_equity_exclude', 'median'),
    count_exclude=('debt_to_assets_exclude', 'size')
)

# Merge the two DataFrames on 'key'
median_ratios_combined = pd.merge(grouped_all, grouped_exclude_zero_debt, on='key', how='outer')

# Extracting SIC, Quarter, and Year using regular expressions, and clean up
pattern = r'(\d+)_([1-4]Q)(\d{4})'
median_ratios_combined[['SIC', 'Quarter', 'Year']] = median_ratios_combined.index.to_series().str.extract(pattern)
median_ratios_combined['Year'] = pd.to_datetime(median_ratios_combined['Year'], format='%Y').dt.year
median_ratios_combined['Quarter'] = median_ratios_combined['Quarter'].str.replace('Q', '').astype(int)

# Sort the DataFrame in reverse chronological order using the Quarter and Year columns
median_ratios_combined = median_ratios_combined.sort_values(by=['Year', 'Quarter'], ascending=[False, False]).reset_index(drop=True)

,debt_to_assets_median_all,debt_to_equity_median_all,count_all,debt_to_assets_median_exclude,debt_to_equity_median_exclude,count_exclude,SIC,Quarter,Year
0,0.000000,0.000000,786,0.083439,0.013485,235.0,283,4,2022
1,0.023289,0.029501,136,0.126533,0.222683,87.0,367,4,2022
2,0.008844,0.000000,19,0.306787,0.536835,10.0,470,4,2022
3,0.000000,0.000000,146,0.148095,0.084721,57.0,737,4,2022
4,0.003885,-0.052764,5,0.012652,-0.291954,4.0,751,4,2022
...,...,...,...,...,...,...,...,...,...
244,0.000000,0.000000,19,0.111341,0.232891,6.0,737,4,2009
245,0.000000,0.000000,13,0.050485,0.084740,5.0,384,3,2009
246,0.003126,0.006741,7,0.011523,0.015685,5.0,738,3,2009
247,0.011703,0.031489,13,0.231302,0.525619,7.0,283,2,2009
248,0.259774,0.630666,1,0.259774,0.630666,1.0,366,2,2009

In [12]:
# Save DataFrame to Excel file
excel_filename = "median_ratios_combined.xlsx"
median_ratios_combined.to_excel(excel_filename, index=False)

print("DataFrame successfully saved to Excel file:", excel_filename)

DataFrame successfully saved to Excel file: median_ratios_combined.xlsx